version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: job-tracker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: -Gowda@789
      MYSQL_DATABASE: job_tracker
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  ai-service:
    build: ./ai-service
    container_name: job-tracker-ai
    ports:
      - "5000:5000"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: job-tracker-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/job_tracker?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: -Gowda@789
      AI_SERVICE_URL: http://ai-service:5000
    depends_on:
      mysql:
        condition: service_healthy
      ai-service:
        condition: service_started
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: job-tracker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data:
